# Generated by Django 3.1.5 on 2021-01-13 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210112_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
